/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.3. DO NOT MODIFY.
*/
module topEntity
    ( // Inputs
      input  c$ds // clock
    , input  c$ds_0 // reset
    , input [7:0] c$ds_1
    , input [7:0] c$ds_2

      // Outputs
    , output wire [7:0] result
    );
  // src/Fractran.hs:15:3-5
  wire [7:0] a;
  // src/Fractran.hs:15:3-5
  wire [7:0] b;
  // src/Fractran.hs:26:1-9
  wire [7:0] acc;
  // src/Fractran.hs:26:1-9
  wire [7:0] frac;

  assign a = acc;

  assign b = frac;

  assign acc = c$ds_1;

  assign frac = c$ds_2;

  assign result = a + b;


endmodule

